#
# This Makefile was generated by Code::Blocks IDE.
#

SRCS_f90d1 = \
ogpf.f90

SRCS_f90d2 = \
demo.f90

OBJS_f90d1 = \
ogpf.o

OBJS_f90d2 = \
demo.o

SRC_DIR_f90d1 = \
./src/

SRC_DIR_f90d2 = \
./example/


OBJS_DIR = ./obj/Debug/
EXE_DIR = ./bin/Debug/

EXE = ogpf.exe
FC = gfortran.exe
LD = gfortran.exe
IDIR = 
CFLAGS = -Wall -std=f2008 -Wl, -J$(OBJS_DIR) $(IDIR)
LFLAGS = 
LIBS = 

VPATH = $(SRC_DIR_f90d1):$(OBJS_DIR):$(SRC_DIR_f90d2)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_f90d1) $(OBJS_f90d2))

all : $(EXE)

$(EXE) : $(OBJS_f90d1) $(OBJS_f90d2)
	@mkdir -p $(EXE_DIR)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_f90d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d1)$(@:.o=.f90) -o $(OBJS_DIR)$@
	
$(OBJS_f90d2):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d2)$(@:.o=.f90) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# Dependencies of files	
demo.o: \
	demo.f90 \
	ogpf.o

ogpf.o: \
	ogpf.f90
